posts/urls.py
from django.urls import path

from posts.views import (
    PostCreateView,
    PostListView,
    PostDetailView,
    CommentView,
    PostDeleteView,
    PostUpdateView,
)

app_name = "posts"

urlpatterns = [
    path("", PostListView.as_view(), name="main"),
    path("create/", PostCreateView.as_view(), name="create"),
    path("<int:pk>/", PostDetailView.as_view(), name="detail"),
    path("<int:pk>/update/", PostUpdateView.as_view(), name="update"),
    path("<int:pk>/delete/", PostDeleteView.as_view(), name="delete"),
    path("<int:pk>/comment/", CommentView.as_view(), name="comment"),
]

simple_blog/urls.py
from django.contrib import admin
from django.urls import path, include

from posts.views import PostListView

urlpatterns = [
    path("posts/", include("posts.urls", namespace="posts")),
    path("user/", include("users.urls", namespace="user")),
    path("admin/", admin.site.urls),
    path("", PostListView.as_view()),
]

users/urls.py
from django.urls import path

from .views import SignUp, LoginView, LogoutView, ProfileUpdateView

app_name = "user"

urlpatterns = [
    path("signup/", SignUp.as_view(), name="signup"),
    path("login/", LoginView.as_view(), name="login"),
    path("logout/", LogoutView.as_view(), name="logout"),
    path("profile/<int:pk>", ProfileUpdateView.as_view(), name="profile"),
]

templates/base.html
{% load static %}

<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Simple Blog</title>
    {% block extra_head %}
    {% endblock %}

    {% load bootstrap4 %} {# import bootstrap4/bootstrap3 #}
    {% bootstrap_css %} {# Embed Bootstrap CSS #}
    {% bootstrap_javascript jquery='full' %}

</head>
<body>
{% include 'header.html' %}
{% if messages %}
    <ul class="messages">
        {% for message in messages %}
            <li{% if message.tags %} class="{{ message.tags }}"{% endif %}>{{ message }}</li>
        {% endfor %}
    </ul>
{% endif %}

<div class="container">
    <div class="row justify-content-center">
        <div class="col-8">
            {% block content %}

            {% endblock %}
        </div>
    </div>
</div>
<script type="text/javascript" src="{% static "ckeditor/ckeditor-init.js" %}"></script>
<script type="text/javascript" src="{% static "ckeditor/ckeditor/ckeditor.js" %}"></script>
<script src="https://code.jquery.com/jquery-3.4.1.slim.min.js"
        integrity="sha384-J6qa4849blE2+poT4WnyKhv5vZF5SrPo0iEjwBvKU7imGFAV0wwj1yYfoRSJoZ+n"
        crossorigin="anonymous"></script>
<script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.0/dist/umd/popper.min.js"
        integrity="sha384-Q6E9RHvbIyZFJoft+2mJbHaEWldlvI9IOYy5n3zV9zzTtmI3UksdQRVvoxMfooAo"
        crossorigin="anonymous"></script>
<script src="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/js/bootstrap.min.js"
        integrity="sha384-wfSDF2E50Y2D1uUdj0O3uMBJnjuUD4Ih7YwaYd1iqfktj0Uod8GCExl3Og8ifwB6"
        crossorigin="anonymous"></script>
</body>
</html>

templates/header.html
<nav class="navbar navbar-expand-lg navbar-dark bg-primary">
    <a class="navbar-brand" href="{% url 'posts:main' %}">Posts</a>
    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarTogglerDemo02"
            aria-controls="navbarTogglerDemo02" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
    </button>

    <div class="collapse navbar-collapse" id="navbarTogglerDemo02">
        <ul class="navbar-nav mr-auto mt-2 mt-lg-0">
        </ul>
        <ul class="navbar-nav mr-0 mt-2 mt-lg-0">
            {% if user.is_authenticated %}
                <li class="nav-item active"><a class="nav-link" href="{% url 'posts:create' %}">Add Posts</a></li>
                <li class="nav-item active"><a class="nav-link" href="{% url 'user:logout' %}">Log out</a></li>
                <li class="nav-item active"><a class="nav-link" href="{% url 'user:profile' pk=user.id %}">My Profile</a></li>
            {% else %}
                <li class="nav-item active"><a class="nav-link" href="{% url 'user:login' %}">Log in</a></li>
                <li class="nav-item active"><a class="nav-link" href="{% url 'user:signup' %}">Sign Up</a></li>
            {% endif %}

        </ul>
    </div>
</nav>